### PR TITLE
Fixes coding style by re-ordering functions

### PR DESCRIPTION
**Pull request by agms-cesar**
- Re-order local methods in header files in order to be in accordance with .c implementation files,
- Re-order static methods in .c implementation files to be in accordance with the local methods calls,
  (The static methods were ordered descending - bottom (first to be called) to top (last to be called)).
- The files which were changed are listed as follow:
  src/knot_cloud.c (implemetation file)
  src/knot_cloud.h (header file)
  src/mq.c
  src/mq.h
  src/parser.c
  src/parser.h

### CODE REVIEW

**Comment by agms-cesar** [comment]
@alla3 @vitbaq please review

**Review by k-cabral — CHANGES_REQUESTED** [review]
I was a little confused by the title and description of 24f2ae7, I believe they could be improved.

Here's a quick suggestion for the title so it gives a better overview of the commit's changes without exceeding the character limit: "Re-order methods in multiple files". You could then describe the general motivation for the change (to fix the coding style) in the commit description.

Also, it could be really useful to list the affected files and go just a bit more in depth about what aspect of the coding style motivated the change in the description.

**Comment by agms-cesar** [comment]
> I was a little confused by the title and description of [24f2ae7](https://github.com/CESARBR/knot-cloud-sdk-c/commit/24f2ae76bc503f6bdc54160cacc8b163354c0d11), I believe they could be improved.
> 
> Here's a quick suggestion for the title so it gives a better overview of the commit's changes without exceeding the character limit: "Re-order methods in multiple files". You could then describe the general motivation for the change (to fix the coding style) in the commit description.
> 
> Also, it could be really useful to list the affected files and go just a bit more in depth about what aspect of the coding style motivated the change in the description.

Indeed. I'll change the commit message in order to make it more easy to understand.

**Comment by agms-cesar** [comment]
> I was a little confused by the title and description of [24f2ae7](https://github.com/CESARBR/knot-cloud-sdk-c/commit/24f2ae76bc503f6bdc54160cacc8b163354c0d11), I believe they could be improved.
> 
> Here's a quick suggestion for the title so it gives a better overview of the commit's changes without exceeding the character limit: "Re-order methods in multiple files". You could then describe the general motivation for the change (to fix the coding style) in the commit description.
> 
> Also, it could be really useful to list the affected files and go just a bit more in depth about what aspect of the coding style motivated the change in the description.

Done

**Review by vitbaq — CHANGES_REQUESTED** [review]
We use 50/72 formatting for the commit message. So, remove the colon char (:) and change and format the message correctly.

The organization pattern from the file knot_cloud.c is different from the file mq.c. In my opinion, the most appropriate is in the knot_cloud.c file. So, in the mq.c file, the first static function should be `attempt_connection()`. But we can discuss about the pattern with the team.

**Comment by agms-cesar** [comment]
> We use 50/72 formatting for the commit message. So, remove the colon char (:) and change and format the message correctly.
> 
> The organization pattern from the file knot_cloud.c is different from the file mq.c. In my opinion, the most appropriate is in the knot_cloud.c file. So, in the mq.c file, the first static function should be `attempt_connection()`. But we can discuss about the pattern with the team.

Done

**Review by k-cabral — CHANGES_REQUESTED** [review]
Ok, it's much better now!
I'm still confused by the idea of local methods in a header file. To me, local methods are the same as static methods... This might be lack of specific knowledge on my part, but calling them "public methods" or "exposed methods" or something like that would still be appropriate and wouldn't require specific knowledge to understand. I'd like to hear more opinions on that, tbh.
Also, please remove the trailing comma, or change it to a period.

**Review by CaioCordeiro — COMMENTED** [review]
LGTM. Nit: i would change the commas to semicolons on the commit messages and add hyphen to create topics.

**Comment by agms-cesar** [comment]
> Ok, it's much better now!
> I'm still confused by the idea of local methods in a header file. To me, local methods are the same as static methods... This might be lack of specific knowledge on my part, but calling them "public methods" or "exposed methods" or something like that would still be appropriate and wouldn't require specific knowledge to understand. I'd like to hear more opinions on that, tbh.
> Also, please remove the trailing comma, or change it to a period.

done

**Comment by agms-cesar** [comment]
> LGTM. Nit: i would change the commas to semicolons on the commit messages and add hyphen to create topics.

agreed. Done

**Review by CaioCordeiro — APPROVED** [review]
LGTM

**Review by vitbaq — APPROVED** [review]

**Review by alla3 — APPROVED** [review]

**Pull request merged**
